specVersion: 0.2.0
name: moonbeam-distribution-subql
version: 0.1.0
description: subquery diction for moonbase-alpha and ...
repository: https://github.com/parallel-finance/moonbeam-distribution-subql
schema:
  file: ./schema.graphql
network:
  genesisHash: ''
  endpoint: wss://moonbeam-alpha.api.onfinality.io/public-ws
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1526695
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
